name: Node.js CI

on:
  push:
    branches: [main, staging, "release/**"]
  pull_request:
    branches: [main, staging, "release/**"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["lts/*"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup environment
        run: mv .env.example .env

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8
          run_install: true

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Run tests
        run: pnpm test
